import AuthGuard from "./component/auth/auth-guard.component"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      <AuthGuard>
      <body>{children}</body>
      </AuthGuard>
    </html>
  )
}
